[project]
name = "handyman5-github-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dateparser>=1.4.0",
    "nikola[extras]>=8.3.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "pyflakes>=3.2.0",
    "pylint>=3.3.6",
    "pylsp-mypy>=0.7.0",
    "python-lsp-server[all]>=1.12.2",
]
