#+BEGIN_COMMENT
.. title: Walking desk, practicum
.. slug: walking-desk-practicum
.. date: 2026-06-13 16:32
.. status: published
#+END_COMMENT

I wanted to get a walking desk setup (variously also known as a treadmill desk or treadmill workstation) so I could get a few more steps in, especially as it's getting to be summertime here and I don't want to go outside during the day if I can possibly avoid it.

I did a lot of research and went down a lot of dead ends, but I found some kit that works for me and I wanted to share in case anybody else was stuck in the same way.

{{{TEASER_END}}}

* tl; dr
:PROPERTIES:
:ID:       4f4df03a-9b26-4acf-986b-c25b3da24b2b
:CREATED:  [2026-06-13 Sat 16:50]
:END:

The [[https://www.amazon.com/dp/B0F9Y3GJ59][Eocnrhe treadmill desk]] and the [[https://www.urevo.com/products/urevo-spacewalk-e1l-treadmill][UREVO Spacewalk E1L walking pad]] are a fine combination; the walking pad can bear my weight, and the desk gets high enough to put a laptop on at a comfortable height (even accounting for the depth of the walking pad) and also tilts to settle the laptop at an appropriate angle. These aren't the sturdiest or highest-quality items, but they definitely get the job done, they work well together, and they were an inexpensive way for me to get started with a walking desk.

* Criteria
:PROPERTIES:
:ID:       e964d62a-58e6-4cce-96e5-138b285e8426
:CREATED:  [2026-06-13 Sat 16:50]
:END:

I had some criteria for both the treadmill/walking pad and for the desk.

**Treadmill**:

- Must be able to support "enough" weight (I don't want to get specific)
- Should be light enough to move out of the way at the end of the workday
- No unnecessary bells and whistles; I'm not trying to go for a run through the virtual countryside, I'm just trying to get in some extra steps

**Desk**:

- Must be height-adjustable
- Must be able to reach a comfortable height, account both for how tall I am and for the depth of the treadmill
- Should be light enough to move out of the way at the end of the workday
- Should be about as narrow as the treadmill (I don't need a wide desk and I'm not putting a monitor on it)
- Should not be electric; I won't be adjusting it often and if I do I can do it by hand

* Research
:PROPERTIES:
:ID:       8dba4f27-d552-4541-ac3f-8b14daf1c506
:CREATED:  [2026-06-13 Sat 16:50]
:END:

** Treadmill
:PROPERTIES:
:ID:       b019c5a3-3fd8-4fed-aabe-acb1b230c8e6
:CREATED:  [2026-06-13 Sat 23:24]
:END:

I started with Wirecutter; even though they were bought out a few years ago, their product reviews are at least a good baseline for learning about what's on the market. They have a [[https://www.nytimes.com/wirecutter/reviews/best-under-desk-treadmills/][best under-desk treadmills]] review which recommends the "Goplus 2 in 1" treadmill. That one is ~80 pounds (so way too heavy to easily move around) and has a running mode (unnecessary bells and whistles). It was also pretty expensive for an experiment.

After doing a ton of research I identified the UREVO line as a good prospect. It was hard to map the product to the actual Amazon page (they're all nothing but buzzwords and none of them have the actual product name in them) but I eventually figured it out. They have several products that I think would be perfectly suitable for my use case, but the [[https://www.urevo.com/products/urevo-spacewalk-e1l-treadmill][UREVO Spacewalk E1L walking pad]] was cromulent and pretty cheap so it got the nod.

** Desk
:PROPERTIES:
:ID:       8585b871-75bd-4cdc-b424-97429aeb8968
:CREATED:  [2026-06-13 Sat 23:24]
:END:

The desk was, believe it or not, much harder to source. Almost everything I found for walking desks assumed I wanted to have a proper desk, with space for a whole workstation, and that I wanted to be able to raise it to standing/walking or lower it to sitting. However, I have a perfectly good desk already that I didn't want to replace for this experiment, so I was looking for a laptop-only desk that was just about as small as it could be.

After a ton of casting about, I found the [[https://www.amazon.com/dp/B0F9Y3GJ59][Eocnrhe treadmill desk]], which seemed incredibly sketchy but did actually arrive as advertised and did exactly what I needed it to do. It's not the sturdiest thing, but it's plenty strong enough to hold a laptop, and I'm not planning to lean on it anyhow.

* Conclusion
:PROPERTIES:
:ID:       378c58fa-7164-4c3a-932a-55deb41a3eff
:CREATED:  [2026-06-13 Sat 23:24]
:END:

Sourcing this equipment was way harder than I expected it to be. I found lots of review sites that seemed to think that this experiment should cost me hundreds or thousands of dollars to start, which I bounced off _hard_. There was also lots of conflicting advice, and almost no manufacturer (neither desks nor treadmills) actually listed all of the relevant information on their websites. Hopefully this saves somebody some of the trouble I went through in figuring this all out.


