on: [push]

jobs:
  nikola_build:
    runs-on: ubuntu-latest
    #container: ghcr.io/handyman5/blog@sha256:167b597df57d3231749c1677cdff2b9e552f68003732893ede98f9709aa26ec9
    permissions:
      contents: write
      id-token: write
      pages: write
    name: 'Deploy Nikola to GitHub Pages'
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Prep pip cache
      run: mkdir -p /tmp/pip/.cache
    - name: Restore Nikola
      id: nikola-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          /tmp/pip/.cache
        key: ${{ runner.os }}-nikola

    # - name: Setup Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.11'
    #     cache: 'pip'
    # - name: Install Nikola
    #   run: pip install "Nikola[extras]"
    - name: Build and Deploy Nikola
      uses: getnikola/nikola-action@v8
      env:
        PIP_CACHE: /tmp/pip/.cache
      with:
        dry_run: true
    - name: Copy Plugin Assets
      run: |-
        find . -type d
        rsync -vP --inplace plugins/*/files/ output/
    - name: Upload Site
      uses: actions/upload-pages-artifact@v3
      with:
        path: "output"
    - name: Publish Site
      uses: actions/deploy-pages@v4
    - name: Save Primes
      id: nikola-save
      uses: actions/cache/save@v4
      with:
        path: |
          /tmp/pip/.cache
        key: ${{ steps.nikola-restore.outputs.cache-primary-key }}
